Duck 8  UI buttons
re-til-dash/shareDuck_ui pull request #10
Opened 2024-07-06 13:18 UTC by BBugHouse

@Sleepingoff 코드 보시고 문제있으시면 코멘트 남겨주세용!

2024-07-07 03:01 UTC, Sleepingoff requested changes
리뷰 내용 댓글로 남깁니다. 대댓글로 이어서 회의해보고 승인으로 변경할게요!

2024-07-07 03:01 UTC, Sleepingoff commented on src/components/molecules/Button/Button.tsx
> +const StyledButton = styled.button`
스타일과 관련된 컴포넌트를 하위로 모으는 건 어떤가요?

2024-07-07 05:45 UTC, BBugHouse commented on src/components/atoms/Icon/Icon.stories.tsx
> +export function Test({ args }: Story) {
기본은 Primary
기능에 따라서 이름 아무렇게 추가하면 좋을 것 같습니다

2024-07-07 05:47 UTC, BBugHouse commented on src/components/atoms/Icon/Icon.stories.tsx
> +const StyeldTextBox = styled.div`
아;; 실수로 Text라고 적어버렸네요
Test입니다 용도는 svg들이 하얀색이라 보는용도로 둔겁니다

2024-07-07 05:48 UTC, BBugHouse commented on src/components/molecules/Button/Button.stories.tsx
> +function log() {
아니요 굳이 로그일 필요는 없습니다.
중복 코드 방지하려고 따로 빼둔겁니다

2024-07-07 05:48 UTC, BBugHouse commented on src/components/molecules/Button/Button.tsx
> +import createTypoStyle from "../../../style/TypoStyle";
좋다고 생각합니다

2024-07-07 05:51 UTC, BBugHouse commented on src/components/molecules/Button/Button.tsx
> +Button.Text = styled.p`
그럼 span으로 할까요?

2024-07-07 05:51 UTC, BBugHouse commented on src/components/molecules/Button/Button.tsx
> +Button.Text = styled.p`
좋은 제안인 것 같습니다

2024-07-07 05:53 UTC, BBugHouse commented on src/components/molecules/Button/Button.tsx
> +const StyledButton = styled.button`
보기 불편합니다

2024-07-07 05:54 UTC, BBugHouse commented on src/components/atoms/Icon/Icon.stories.tsx
> +const StyeldTextBox = styled.div`
얘도 같이 수정하겠습니다

2024-07-07 06:02 UTC, BBugHouse commented on src/components/molecules/Button/Button.tsx
> +const Button = ({ onClick, children }: typeButtonProps) => {
어떤 컨벤션 말씀하시는지 잘 모르겠습니다

2024-07-08 02:58 UTC, Sleepingoff commented on src/components/atoms/Icon/Icon.stories.tsx
> +export function Test({ args }: Story) {
그럼 스토리북 이름만 본다면 어떤 컴포넌트인지 알 수가 없지 않나요? 마지막에 Story 붙이는 건 어떤가요?

2024-07-08 02:59 UTC, Sleepingoff commented on src/components/molecules/Button/Button.stories.tsx
> +function log() {
그럼 클릭 이벤트 함수로 보고 handleClick으로 시작해야하지 않을까해서요!

2024-07-08 03:00 UTC, Sleepingoff commented on src/components/molecules/Button/Button.tsx
> +import createTypoStyle from "../../../style/TypoStyle";
지라에 올려줄게요!

2024-07-08 03:01 UTC, Sleepingoff commented on src/components/molecules/Button/Button.tsx
> +const Button = ({ onClick, children }: typeButtonProps) => {
컴포넌트는 function으로 하기로 했던 거요!

2024-07-08 03:02 UTC, Sleepingoff commented on src/components/molecules/Button/Button.tsx
> +const StyledButton = styled.button`
이 부분 자세하게 말하면 좋을 것 같아요! 시간될 때 회의를 합시다ㅎㅎ

2024-07-08 03:03 UTC, BBugHouse commented on src/components/atoms/Icon/Icon.stories.tsx
> +export function Test({ args }: Story) {
어차피 스토리북 컴포넌트만 내보내는데 모르진 않을 것 같습니다

2024-07-08 03:03 UTC, BBugHouse commented on src/components/atoms/Icon/Icon.stories.tsx
> +export function Test({ args }: Story) {
근데 확실히 구분되면 좋으니 일단 그렇게 정하죠

2024-07-08 03:05 UTC, BBugHouse commented on src/components/molecules/Button/Button.stories.tsx
> +function log() {
로그를 띄운다 한가지 기능밖에 안하기도 하고 바꿀 일도 없습니다
따라서 명확하고 직관적인 로그가 낫다고 생각합니다.
handleClick은 클릭함수라는 점은 명확하지만 로그를 찍는다는것을 표현을 못해주니까요

2024-07-08 03:05 UTC, BBugHouse commented on src/components/molecules/Button/Button.tsx
> +const Button = ({ onClick, children }: typeButtonProps) => {
복붙 이슈.. 이것도 해결하고 올리겠습니다

2024-07-08 03:06 UTC, BBugHouse commented on src/components/molecules/Button/Button.tsx
> +const StyledButton = styled.button`
넵

2024-07-08 03:06 UTC, BBugHouse commented on src/components/molecules/Button/Button.tsx
> +const Button = ({ onClick, children }: typeButtonProps) => {
prettier도입해서 피하게 자동으로 해둘까요

2024-07-08 03:07 UTC, Sleepingoff commented on src/components/atoms/Icon/Icon.stories.tsx
> +export function Test({ args }: Story) {
컴포넌트 이름은 디자이너분이 잘 이해할 수 있도록하는게 좋을 것 같고, 단순히 PRIMARY로 하게 되면 어떤 컴포넌트인지 알 이름만 가지고는 알 수가 없어서 안 좋은 네이밍이라고 생각합니다!

2024-07-08 03:09 UTC, BBugHouse commented on src/components/atoms/Icon/Icon.stories.tsx
> +export function Test({ args }: Story) {
스토리북에서 컴포넌트 이름이 어차피 지정되있기는 한데... 그안에서 기능하는것들을 나누는거여서 가장 기본을 primary라고 하는거죠 보통
디자인쪽에서도 자주쓰는걸로 알고 있습니다

2024-07-08 03:09 UTC, Sleepingoff commented on src/components/molecules/Button/Button.tsx
> +const Button = ({ onClick, children }: typeButtonProps) => {
넵 좋습니다

2024-07-08 03:10 UTC, BBugHouse commented on src/components/molecules/Button/Button.stories.tsx
> +function log() {
그러네요 이부분도 생각을 못했습니다. 피드백 감사합니다 :)

2024-07-08 03:11 UTC, Sleepingoff commented on src/components/atoms/Icon/Icon.stories.tsx
> +export function Test({ args }: Story) {
그렇다면 default가 있습니다. primary, secondary, default(or basic) 등 variant를 나타내는 단어이기 때문에 특정 variant가 필요없는 경우에 대해서 네이밍이 별도로 필요하지 않을까 싶었어요.

2024-07-08 03:14 UTC, BBugHouse commented on src/components/atoms/Icon/Icon.stories.tsx
> +export function Test({ args }: Story) {
알겠습니다 예전에 Default로 하다가 뭐랑 충돌난 기억이 있어서 이렇게 했었는데
다시 보이면 그떄 생각해보죠

2024-07-08 03:15 UTC, Sleepingoff commented on src/components/atoms/Icon/Icon.stories.tsx
> +export function Test({ args }: Story) {
넵!

2024-07-08 03:16 UTC, Sleepingoff commented
@BBugHouse 새로 PR올리실 건가요? 커밋을 추가할 건가요?

2024-07-08 03:16 UTC, BBugHouse commented
@Sleepingoff 추가해서 올립니다

2024-07-08 03:58 UTC, Sleepingoff approved these changes
확인 완료했습니다!

2024-07-08 03:58 UTC, Sleepingoff commented on src/style/TypoStyle.tsx
> +  // 글로벌 폰트 작동 안하는중
아마 폰트 파일이 없어서 그런 걸로 알고 있습니다

2024-07-08 03:58 UTC, Sleepingoff commented on src/components/atoms/Icon/Icon.stories.tsx
> +}
다크모드에 대해서 하고 싶다면 스토리북 설정 파일중 preview에 themeprovier를 넣으면 되는 걸로 알고 있어용

2024-07-08 04:01 UTC, BBugHouse commented on src/style/TypoStyle.tsx
> +  // 글로벌 폰트 작동 안하는중
임시로 저렇게 추가해뒀습니다 나중에 수정하든가 하죠

2024-07-08 04:01 UTC, BBugHouse commented on src/components/atoms/Icon/Icon.stories.tsx
> +}
제가 주석도 해놨지만 다크모드때문에 한게 아니라 화이트모드에서 아이콘 svg가 안보여서 네모박스 만들어둔겁니다

2024-07-08 04:02 UTC, Sleepingoff commented on src/style/TypoStyle.tsx
> +  // 글로벌 폰트 작동 안하는중
넵

2024-07-08 04:03 UTC, Sleepingoff commented on src/components/atoms/Icon/Icon.stories.tsx
> +}
아하 그렇군요 확인했습니다!

2024-07-08 04:47 UTC, merged